[test]
preload = ["./packages/core/tests/__preload__/happydom.ts", "./packages/core/tests/__preload__/svelteLoader.ts", "./packages/core/tests/__preload__/obsidianMock.ts", "./packages/core/tests/__preload__/customMatchers.ts"]
root = "./packages/core/tests"
coverage = true
coverageReporter = ["text", "lcov"]